//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CinemaApp.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ActorsFilms
    {
        public int IdActorsFilms { get; set; }
        public int FilmId { get; set; }
        public int ActorId { get; set; }
    
        public virtual Actors Actors { get; set; }
        public virtual Films Films { get; set; }
    }
}
