//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CinemaApp.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Admins
    {
        public int IdAdmin { get; set; }
        public string AdminLogin { get; set; }
        public string AdminPassword { get; set; }
        public string AdminName { get; set; }
        public string AdminSurname { get; set; }
        public string AdminPatronymic { get; set; }
    }
}
