//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CinemaApp.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FilmsDBEntities : DbContext
    {
        public FilmsDBEntities()
            : base("name=FilmsDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Actors> Actors { get; set; }
        public virtual DbSet<ActorsFilms> ActorsFilms { get; set; }
        public virtual DbSet<Admins> Admins { get; set; }
        public virtual DbSet<AgeLimits> AgeLimits { get; set; }
        public virtual DbSet<Countries> Countries { get; set; }
        public virtual DbSet<Employees> Employees { get; set; }
        public virtual DbSet<Films> Films { get; set; }
        public virtual DbSet<FilmsGeners> FilmsGeners { get; set; }
        public virtual DbSet<Firms> Firms { get; set; }
        public virtual DbSet<Genders> Genders { get; set; }
        public virtual DbSet<Genres> Genres { get; set; }
        public virtual DbSet<Halls> Halls { get; set; }
        public virtual DbSet<Posts> Posts { get; set; }
        public virtual DbSet<Requirements> Requirements { get; set; }
        public virtual DbSet<RequirementsEmployees> RequirementsEmployees { get; set; }
        public virtual DbSet<Responsibilities> Responsibilities { get; set; }
        public virtual DbSet<ResponsibilitiesEmployees> ResponsibilitiesEmployees { get; set; }
        public virtual DbSet<Seances> Seances { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Tickets> Tickets { get; set; }
    }
}
