//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CinemaApp.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Responsibilities
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Responsibilities()
        {
            this.ResponsibilitiesEmployees = new HashSet<ResponsibilitiesEmployees>();
        }
    
        public int IdResponsibilities { get; set; }
        public string ResponsibilityName { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ResponsibilitiesEmployees> ResponsibilitiesEmployees { get; set; }
    }
}
