//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CinemaLibraryTests.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employees
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Employees()
        {
            this.RequirementsEmployees = new HashSet<RequirementsEmployees>();
            this.ResponsibilitiesEmployees = new HashSet<ResponsibilitiesEmployees>();
        }
    
        public int IdEmployee { get; set; }
        public string EmployeeName { get; set; }
        public string EmployeeSurname { get; set; }
        public string EmployeePatronymic { get; set; }
        public int EmployeeAge { get; set; }
        public int GenderId { get; set; }
        public string EmployeeAdress { get; set; }
        public string EmployeePhone { get; set; }
        public string EmployeePassportSeria { get; set; }
        public string EmployeePassportNumber { get; set; }
        public int PostId { get; set; }
        public double EmployeeSalary { get; set; }
    
        public virtual Genders Genders { get; set; }
        public virtual Posts Posts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RequirementsEmployees> RequirementsEmployees { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ResponsibilitiesEmployees> ResponsibilitiesEmployees { get; set; }
    }
}
