//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CinemaLibraryTests.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tickets
    {
        public int IdTicket { get; set; }
        public int SeanceId { get; set; }
        public int TicketPlace { get; set; }
        public int TicketRow { get; set; }
        public double TicketCost { get; set; }
        public System.DateTime TicketPayDate { get; set; }
        public Nullable<int> TicketType { get; set; }
    
        public virtual Seances Seances { get; set; }
    }
}
